In [7]:
# Matrix Operations with NumPy

import numpy as np

# Exercise 1: Matrix Addition & Subtraction
# Define two 3x3 matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform addition
addition_result = A + B
print("Addition Result:\n", addition_result)

# Perform subtraction
subtraction_result = A - B
print("Subtraction Result:\n", subtraction_result)

Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction Result:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [8]:
# Exercise 2: Matrix Multiplication
# Define two compatible matrices for multiplication
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([[7, 8], [9, 10], [11, 12]])

# Perform multiplication
multiplication_result = np.dot(C, D)
print("Multiplication Result:\n", multiplication_result)

Multiplication Result:
 [[ 58  64]
 [139 154]]


In [9]:
# Exercise 3: Matrix Transpose
# Create a 2x3 matrix
E = np.array([[1, 2, 3], [4, 5, 6]])

# Find its transpose
transpose_result = E.T
print("Transpose Result:\n", transpose_result)

Transpose Result:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
# Exercise 4: Calculating the Determinant
# Create a 3x3 matrix
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the determinant
determinant_result = np.linalg.det(F)
print("Determinant Result:\n", determinant_result)


Determinant Result:
 0.0


In [11]:
# Exercise 5: Finding the Inverse
# Create a 3x3 invertible matrix
G = np.array([[4, 7, 2], [3, 6, 1], [2, 5, 8]])

# Calculate its inverse
inverse_result = np.linalg.inv(G)
print("Inverse Result:\n", inverse_result)



Inverse Result:
 [[ 1.79166667 -1.91666667 -0.20833333]
 [-0.91666667  1.16666667  0.08333333]
 [ 0.125      -0.25        0.125     ]]


In [12]:
# Additional Challenge: Implementing Matrix Multiplication Manually
def manual_matrix_multiplication(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Ensure matrix dimensions are compatible
    if cols_A != rows_B:
        raise ValueError("Incompatible matrix dimensions for multiplication")

    # Initialize result matrix with zeros
    result = np.zeros((rows_A, cols_B))

    # Nested loops for matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Example matrices for manual multiplication
H = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[7, 8], [9, 10], [11, 12]])

# Perform manual multiplication
manual_result = manual_matrix_multiplication(H, I)
print("Manual Multiplication Result:\n", manual_result)

# Generating Random Matrices and Performing Operations
random_matrix_A = np.random.rand(10, 10)
random_matrix_B = np.random.rand(10, 10)

# Addition
random_addition = random_matrix_A + random_matrix_B
print("Random Matrix Addition:\n", random_addition)

# Subtraction
random_subtraction = random_matrix_A - random_matrix_B
print("Random Matrix Subtraction:\n", random_subtraction)

# Matrix Multiplication
random_multiplication = np.dot(random_matrix_A, random_matrix_B)
print("Random Matrix Multiplication:\n", random_multiplication)

# Transpose
random_transpose_A = random_matrix_A.T
print("Transpose of Random Matrix A:\n", random_transpose_A)


Manual Multiplication Result:
 [[ 58.  64.]
 [139. 154.]]
Random Matrix Addition:
 [[0.55213923 1.07114493 1.15886416 1.44319777 1.53879997 1.89636886
  0.31462944 1.63408254 1.59868025 0.76639423]
 [0.76107231 0.77738156 1.20600408 1.07768645 1.12852973 1.05864992
  1.10009994 0.39954425 0.83264738 1.36431705]
 [0.43672544 0.03990794 0.68156457 0.31911357 1.68260564 0.70255374
  1.52980566 0.98128628 0.62688692 0.41173628]
 [1.15610898 1.07542219 1.15444174 0.82898006 1.22819805 1.30037559
  0.84153373 1.55143871 0.82104395 0.69284205]
 [0.97048011 0.62649962 0.84393775 0.63476193 0.602665   1.06672348
  1.2557375  0.70163333 0.64572024 0.95002252]
 [0.98944181 0.41403195 1.26610926 1.24488088 0.50174333 0.87837163
  1.08022195 1.60998679 0.99281777 1.19658635]
 [0.83840219 0.47085926 1.34225086 0.66924717 1.18816171 1.12001413
  1.34407209 1.20867063 1.02105518 0.84402111]
 [1.12720158 1.69664186 0.81672515 0.35648944 0.57319532 0.79766219
  1.21196769 0.93505988 0.8880988  0.2888358